### PR TITLE
Initial

### PR DESCRIPTION
**Pull request by EswarWiser**

### CODE REVIEW

**Comment by EswarWiser** [comment]
atlantis plan

**Comment by ansible360** [comment]
```
Error: This repo is not allowlisted for Atlantis.
```

**Comment by EswarWiser** [comment]
atlantis plan

**Comment by ansible360** [comment]
**Plan Error**
```
looking for atlantis.yaml file in "/home/atlantis/.atlantis/repos/EswarWiser/Atlantis-Actions-Test/1/default": found "atlantis.yml" as config file; rename using the .yaml extension - "atlantis.yaml"
```

**Comment by EswarWiser** [comment]
atlantis plan

**Comment by ansible360** [comment]
Ran Plan for 0 projects:

**Comment by EswarWiser** [comment]
atlantis plan

**Comment by ansible360** [comment]
**Plan Error**
```
The default workspace is currently locked by another command that is running for this pull request.
Wait until the previous command is complete and try again.
```

**Comment by ansible360** [comment]
Ran Plan for dir: `atlantis` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/home/atlantis/.atlantis/bin/terraform1.0.8 plan -input=false -refresh -no-color -out \"/home/atlantis/.atlantis/repos/EswarWiser/Atlantis-Actions-Test/1/default/atlantis/atlantis-default.tfplan\"" in "/home/atlantis/.atlantis/repos/EswarWiser/Atlantis-Actions-Test/1/default/atlantis": exit status 1

Warning: Argument is deprecated

  with module.atlantis.module.atlantis.module.vpc.aws_eip.nat,
  on .terraform/modules/atlantis.atlantis.vpc/main.tf line 1068, in resource "aws_eip" "nat":
1068:   vpc = true

use domain attribute instead

Error: Unsupported argument

  on .terraform/modules/atlantis.atlantis.ecs/main.tf line 6, in resource "aws_ecs_cluster" "this":
   6:   capacity_providers = var.capacity_providers

An argument named "capacity_providers" is not expected here.

Error: Unsupported block type

  on .terraform/modules/atlantis.atlantis.ecs/main.tf line 8, in resource "aws_ecs_cluster" "this":
   8:   dynamic "default_capacity_provider_strategy" {

Blocks of type "default_capacity_provider_strategy" are not expected here.

Error: Unsupported argument

  on .terraform/modules/atlantis.atlantis.vpc/main.tf line 32, in resource "aws_vpc" "this":
  32:   enable_classiclink               = var.enable_classiclink

An argument named "enable_classiclink" is not expected here.

Error: Unsupported argument

  on .terraform/modules/atlantis.atlantis.vpc/main.tf line 33, in resource "aws_vpc" "this":
  33:   enable_classiclink_dns_support   = var.enable_classiclink_dns_support

An argument named "enable_classiclink_dns_support" is not expected here.

Error: Unsupported argument

  on .terraform/modules/atlantis.atlantis.vpc/main.tf line 1307, in resource "aws_default_vpc" "this":
1307:   enable_classiclink   = var.default_vpc_enable_classiclink

An argument named "enable_classiclink" is not expected here.

```
</details>

**Comment by EswarWiser** [comment]
atlantis plan

**Comment by EswarWiser** [comment]
atlantris plan

**Comment by EswarWiser** [comment]
atlantis plan

**Comment by ansible360** [comment]
Ran Plan for dir: `atlantis` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/home/atlantis/.atlantis/bin/terraform1.0.8 plan -input=false -refresh -no-color -out \"/home/atlantis/.atlantis/repos/EswarWiser/Atlantis-Actions-Test/1/default/atlantis/atlantis-default.tfplan\"" in "/home/atlantis/.atlantis/repos/EswarWiser/Atlantis-Actions-Test/1/default/atlantis": exit status 1

Warning: Argument is deprecated

  with module.atlantis.module.atlantis.module.vpc.aws_eip.nat,
  on .terraform/modules/atlantis.atlantis.vpc/main.tf line 1068, in resource "aws_eip" "nat":
1068:   vpc = true

use domain attribute instead

Error: Unsupported argument

  on .terraform/modules/atlantis.atlantis.ecs/main.tf line 6, in resource "aws_ecs_cluster" "this":
   6:   capacity_providers = var.capacity_providers

An argument named "capacity_providers" is not expected here.

Error: Unsupported block type

  on .terraform/modules/atlantis.atlantis.ecs/main.tf line 8, in resource "aws_ecs_cluster" "this":
   8:   dynamic "default_capacity_provider_strategy" {

Blocks of type "default_capacity_provider_strategy" are not expected here.

Error: Unsupported argument

  on .terraform/modules/atlantis.atlantis.vpc/main.tf line 32, in resource "aws_vpc" "this":
  32:   enable_classiclink               = var.enable_classiclink

An argument named "enable_classiclink" is not expected here.

Error: Unsupported argument

  on .terraform/modules/atlantis.atlantis.vpc/main.tf line 33, in resource "aws_vpc" "this":
  33:   enable_classiclink_dns_support   = var.enable_classiclink_dns_support

An argument named "enable_classiclink_dns_support" is not expected here.

Error: Unsupported argument

  on .terraform/modules/atlantis.atlantis.vpc/main.tf line 1307, in resource "aws_default_vpc" "this":
1307:   enable_classiclink   = var.default_vpc_enable_classiclink

An argument named "enable_classiclink" is not expected here.

```
</details>

**Comment by ansible360** [comment]
Ran Plan for dir: `atlantis` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/home/atlantis/.atlantis/bin/terraform1.0.8 plan -input=false -refresh -no-color -out \"/home/atlantis/.atlantis/repos/EswarWiser/Atlantis-Actions-Test/1/default/atlantis/atlantis-default.tfplan\"" in "/home/atlantis/.atlantis/repos/EswarWiser/Atlantis-Actions-Test/1/default/atlantis": exit status 1

Warning: Argument is deprecated

  with module.atlantis.module.atlantis.module.vpc.aws_eip.nat,
  on .terraform/modules/atlantis.atlantis.vpc/main.tf line 1068, in resource "aws_eip" "nat":
1068:   vpc = true

use domain attribute instead

Error: Unsupported argument

  on .terraform/modules/atlantis.atlantis.ecs/main.tf line 6, in resource "aws_ecs_cluster" "this":
   6:   capacity_providers = var.capacity_providers

An argument named "capacity_providers" is not expected here.

Error: Unsupported block type

  on .terraform/modules/atlantis.atlantis.ecs/main.tf line 8, in resource "aws_ecs_cluster" "this":
   8:   dynamic "default_capacity_provider_strategy" {

Blocks of type "default_capacity_provider_strategy" are not expected here.

Error: Unsupported argument

  on .terraform/modules/atlantis.atlantis.vpc/main.tf line 32, in resource "aws_vpc" "this":
  32:   enable_classiclink               = var.enable_classiclink

An argument named "enable_classiclink" is not expected here.

Error: Unsupported argument

  on .terraform/modules/atlantis.atlantis.vpc/main.tf line 33, in resource "aws_vpc" "this":
  33:   enable_classiclink_dns_support   = var.enable_classiclink_dns_support

An argument named "enable_classiclink_dns_support" is not expected here.

Error: Unsupported argument

  on .terraform/modules/atlantis.atlantis.vpc/main.tf line 1307, in resource "aws_default_vpc" "this":
1307:   enable_classiclink   = var.default_vpc_enable_classiclink

An argument named "enable_classiclink" is not expected here.

```
</details>

**Comment by ansible360** [comment]
Ran Plan for dir: `atlantis` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/home/atlantis/.atlantis/bin/terraform1.0.8 plan -input=false -refresh -no-color -out \"/home/atlantis/.atlantis/repos/EswarWiser/Atlantis-Actions-Test/1/default/atlantis/atlantis-default.tfplan\"" in "/home/atlantis/.atlantis/repos/EswarWiser/Atlantis-Actions-Test/1/default/atlantis": exit status 1

Warning: Argument is deprecated

  with module.atlantis.module.atlantis.module.vpc.aws_eip.nat,
  on .terraform/modules/atlantis.atlantis.vpc/main.tf line 1068, in resource "aws_eip" "nat":
1068:   vpc = true

use domain attribute instead

Error: Unsupported argument

  on .terraform/modules/atlantis.atlantis.ecs/main.tf line 6, in resource "aws_ecs_cluster" "this":
   6:   capacity_providers = var.capacity_providers

An argument named "capacity_providers" is not expected here.

Error: Unsupported block type

  on .terraform/modules/atlantis.atlantis.ecs/main.tf line 8, in resource "aws_ecs_cluster" "this":
   8:   dynamic "default_capacity_provider_strategy" {

Blocks of type "default_capacity_provider_strategy" are not expected here.

Error: Unsupported argument

  on .terraform/modules/atlantis.atlantis.vpc/main.tf line 32, in resource "aws_vpc" "this":
  32:   enable_classiclink               = var.enable_classiclink

An argument named "enable_classiclink" is not expected here.

Error: Unsupported argument

  on .terraform/modules/atlantis.atlantis.vpc/main.tf line 33, in resource "aws_vpc" "this":
  33:   enable_classiclink_dns_support   = var.enable_classiclink_dns_support

An argument named "enable_classiclink_dns_support" is not expected here.

Error: Unsupported argument

  on .terraform/modules/atlantis.atlantis.vpc/main.tf line 1307, in resource "aws_default_vpc" "this":
1307:   enable_classiclink   = var.default_vpc_enable_classiclink

An argument named "enable_classiclink" is not expected here.

```
</details>

**Comment by ansible360** [comment]
Ran Plan for dir: `atlantis` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/home/atlantis/.atlantis/bin/terraform1.0.8 plan -input=false -refresh -no-color -out \"/home/atlantis/.atlantis/repos/EswarWiser/Atlantis-Actions-Test/1/default/atlantis/atlantis-default.tfplan\"" in "/home/atlantis/.atlantis/repos/EswarWiser/Atlantis-Actions-Test/1/default/atlantis": exit status 1

Warning: Argument is deprecated

  with module.atlantis.module.atlantis.module.vpc.aws_eip.nat,
  on .terraform/modules/atlantis.atlantis.vpc/main.tf line 1068, in resource "aws_eip" "nat":
1068:   vpc = true

use domain attribute instead

Error: Unsupported argument

  on .terraform/modules/atlantis.atlantis.ecs/main.tf line 6, in resource "aws_ecs_cluster" "this":
   6:   capacity_providers = var.capacity_providers

An argument named "capacity_providers" is not expected here.

Error: Unsupported block type

  on .terraform/modules/atlantis.atlantis.ecs/main.tf line 8, in resource "aws_ecs_cluster" "this":
   8:   dynamic "default_capacity_provider_strategy" {

Blocks of type "default_capacity_provider_strategy" are not expected here.

Error: Unsupported argument

  on .terraform/modules/atlantis.atlantis.vpc/main.tf line 32, in resource "aws_vpc" "this":
  32:   enable_classiclink               = var.enable_classiclink

An argument named "enable_classiclink" is not expected here.

Error: Unsupported argument

  on .terraform/modules/atlantis.atlantis.vpc/main.tf line 33, in resource "aws_vpc" "this":
  33:   enable_classiclink_dns_support   = var.enable_classiclink_dns_support

An argument named "enable_classiclink_dns_support" is not expected here.

Error: Unsupported argument

  on .terraform/modules/atlantis.atlantis.vpc/main.tf line 1307, in resource "aws_default_vpc" "this":
1307:   enable_classiclink   = var.default_vpc_enable_classiclink

An argument named "enable_classiclink" is not expected here.

```
</details>

**Comment by ansible360** [comment]
Ran Plan for dir: `atlantis` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/home/atlantis/.atlantis/bin/terraform1.0.8 plan -input=false -refresh -no-color -out \"/home/atlantis/.atlantis/repos/EswarWiser/Atlantis-Actions-Test/1/default/atlantis/atlantis-default.tfplan\"" in "/home/atlantis/.atlantis/repos/EswarWiser/Atlantis-Actions-Test/1/default/atlantis": exit status 1

Warning: Argument is deprecated

  with module.atlantis.module.atlantis.module.vpc.aws_eip.nat,
  on .terraform/modules/atlantis.atlantis.vpc/main.tf line 1068, in resource "aws_eip" "nat":
1068:   vpc = true

use domain attribute instead

Error: Unsupported argument

  on .terraform/modules/atlantis.atlantis.ecs/main.tf line 6, in resource "aws_ecs_cluster" "this":
   6:   capacity_providers = var.capacity_providers

An argument named "capacity_providers" is not expected here.

Error: Unsupported block type

  on .terraform/modules/atlantis.atlantis.ecs/main.tf line 8, in resource "aws_ecs_cluster" "this":
   8:   dynamic "default_capacity_provider_strategy" {

Blocks of type "default_capacity_provider_strategy" are not expected here.

Error: Unsupported argument

  on .terraform/modules/atlantis.atlantis.vpc/main.tf line 32, in resource "aws_vpc" "this":
  32:   enable_classiclink               = var.enable_classiclink

An argument named "enable_classiclink" is not expected here.

Error: Unsupported argument

  on .terraform/modules/atlantis.atlantis.vpc/main.tf line 33, in resource "aws_vpc" "this":
  33:   enable_classiclink_dns_support   = var.enable_classiclink_dns_support

An argument named "enable_classiclink_dns_support" is not expected here.

Error: Unsupported argument

  on .terraform/modules/atlantis.atlantis.vpc/main.tf line 1307, in resource "aws_default_vpc" "this":
1307:   enable_classiclink   = var.default_vpc_enable_classiclink

An argument named "enable_classiclink" is not expected here.

```
</details>

**Comment by ansible360** [comment]
Ran Plan for dir: `atlantis` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/home/atlantis/.atlantis/bin/terraform1.0.8 plan -input=false -refresh -no-color -out \"/home/atlantis/.atlantis/repos/EswarWiser/Atlantis-Actions-Test/1/default/atlantis/atlantis-default.tfplan\"" in "/home/atlantis/.atlantis/repos/EswarWiser/Atlantis-Actions-Test/1/default/atlantis": exit status 1

Warning: Argument is deprecated

  with module.atlantis.module.atlantis.module.vpc.aws_eip.nat,
  on .terraform/modules/atlantis.atlantis.vpc/main.tf line 1068, in resource "aws_eip" "nat":
1068:   vpc = true

use domain attribute instead

Error: Unsupported argument

  on .terraform/modules/atlantis.atlantis.ecs/main.tf line 6, in resource "aws_ecs_cluster" "this":
   6:   capacity_providers = var.capacity_providers

An argument named "capacity_providers" is not expected here.

Error: Unsupported block type

  on .terraform/modules/atlantis.atlantis.ecs/main.tf line 8, in resource "aws_ecs_cluster" "this":
   8:   dynamic "default_capacity_provider_strategy" {

Blocks of type "default_capacity_provider_strategy" are not expected here.

Error: Unsupported argument

  on .terraform/modules/atlantis.atlantis.vpc/main.tf line 32, in resource "aws_vpc" "this":
  32:   enable_classiclink               = var.enable_classiclink

An argument named "enable_classiclink" is not expected here.

Error: Unsupported argument

  on .terraform/modules/atlantis.atlantis.vpc/main.tf line 33, in resource "aws_vpc" "this":
  33:   enable_classiclink_dns_support   = var.enable_classiclink_dns_support

An argument named "enable_classiclink_dns_support" is not expected here.

Error: Unsupported argument

  on .terraform/modules/atlantis.atlantis.vpc/main.tf line 1307, in resource "aws_default_vpc" "this":
1307:   enable_classiclink   = var.default_vpc_enable_classiclink

An argument named "enable_classiclink" is not expected here.

```
</details>

**Pull request closed without merging**
